# redis-ha:
#   enabled: true

global:
  domain: argocd.mikael.localhost

controller:
  replicas: 1

server:
  ingress:
    enabled: true
    tls: false
    ingressClassName: nginx
    hosts:
      - argocd.mikael.localhost
    annotations:
      kubernetes.io/ingress.class: "nginx"
      # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8080

nginx:
  ingress:
    kubernetes.io/force-ssl-redirect: true
    ingress.kubernetes.io/ssl-passthrough: true


# server:
#   replicas: 1
#   service:
#     type: LoadBalancer

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1