# redis-ha:
#   enabled: true

global:
  domain: argocd.mikael.localhost

controller:
  replicas: 1

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.mikael.localhost
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.mikael.localhost
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8080
      - name: https
        port: 443
        protocol: TCP
        targetPort: 80443

# nginx:
#   ingress:
#     kubernetes.io/force-ssl-redirect: true
#     ingress.kubernetes.io/ssl-passthrough: true


# server:
#   replicas: 1
#   service:
#     type: LoadBalancer

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1