# redis-ha:
#   enabled: true

global:
  domain: argocd.mikael.localhost.

controller:
  replicas: 1

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - argocd.mikael.localhost
    tls: false

  service:
    type: ClusterIP
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080

# server:
#   replicas: 1
#   service:
#     type: LoadBalancer

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1