# redis-ha:
#   enabled: true

global:
  domain: argocd.mikael.localhost.

controller:
  replicas: 1

server:
  ingress:
    enabled: true
    tls: true
  ingressClassName: ingress-external
  service:
    enabled: true
    type: ClusterIP
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app.kubernetes.io/name: argocd-server
    nodePortHttp: 30080
    nodePortHttps: 30443

nginx:
  ingress:
    kubernetes.io/force-ssl-redirect: true
    ingress.kubernetes.io/ssl-passthrough: true


# server:
#   replicas: 1
#   service:
#     type: LoadBalancer

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1