global:
  domain: argocd.mikael.localhost

configs:
  params:
    server.insecure: false

server:
  ingress:
    enabled: true
    controller: generic
    ingressClassName: internal
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    extraTls:
      - hosts:
        - argocd.mikael.localhost
        # Based on the ingress controller used secret might be optional
        secretName: argocd-tls